server:
  name: go-mongo-rest-api
  port: 8080

mongo:
  uri: mongodb+srv://tube:abcd1234@cluster0.cirxd.mongodb.net/tube?retryWrites=true&w=majority
  database: tube

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size
  
key: AIzaSyDVRw8jjqyJWijg57zXSOMpUArlZGpC7bE